on:
  push:
    branches:
      - main
  pull_request:
name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test
        # set sell to bash for "set -eo pipefail"
        shell: bash
        run: go test -v -shuffle=on -race -json ./... | tee test.json
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.7.0
        with:
          test-results: test.json
